# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='currencies',
            name='rates',
            field=models.ManyToManyField(blank=True, null=True, related_name='currency', to='CurrencyApp.Rates'),
        ),
    ]
